-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 19:33:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema batabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema batabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `batabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `batabase` ;

-- -----------------------------------------------------
-- Table `batabase`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`clientes` ;

CREATE TABLE IF NOT EXISTS `batabase`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `contrasenya` VARCHAR(100) NOT NULL,
  `administrador` INT NULL DEFAULT NULL,
  `codigopostal` INT NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `localidad` VARCHAR(45) NULL DEFAULT NULL,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batabase`.`descuentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`descuentos` ;

CREATE TABLE IF NOT EXISTS `batabase`.`descuentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NULL DEFAULT NULL,
  `porcentaje` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batabase`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`historial` ;

CREATE TABLE IF NOT EXISTS `batabase`.`historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batabase`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `batabase`.`pedidos` (
  `id_cliente` INT NULL DEFAULT NULL,
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_descuento` INT NULL DEFAULT NULL,
  `localidad` VARCHAR(32) NULL DEFAULT NULL,
  `codigopostal` INT NULL DEFAULT NULL,
  `calle` VARCHAR(32) NULL DEFAULT NULL,
  `nombre` VARCHAR(32) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `precio` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `batabase`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batabase`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`productos` ;

CREATE TABLE IF NOT EXISTS `batabase`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batabase`.`productos_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batabase`.`productos_pedidos` ;

CREATE TABLE IF NOT EXISTS `batabase`.`productos_pedidos` (
  `id_pedido` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  INDEX `id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `batabase`.`pedidos` (`id_pedido`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `batabase`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
